[build]
target = "index.html"
dist = "dist"
public_url = "/exquisite-verse/"

[serve]
address = "127.0.0.1"
port = 8080
open = true

[[serve.mime_types]]
extension = "js"
mime_type = "application/javascript"

[[serve.mime_types]]
extension = "wasm"
mime_type = "application/wasm"

[watch]
watch = ["src", "index.html"]
