[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[serve]
address = "127.0.0.1"
port = 8080
open = true

# Add MIME type configuration
[[serve.mime_types]]
extension = "js"
mime_type = "application/javascript"

[[hooks]]
stage = "build"
command = "wasm-bindgen"
command_arguments = ["--target", "web", "--out-dir", "./dist/pkg", "target/wasm32-unknown-unknown/debug/exquisite_verse.wasm"]

[watch]
watch = ["src", "index.html"] 